### ISSUE TITLE
gisaid下载问题

### ISSUE THREAD

**Issue by scwwxc** [c4-driod/GISAID-spiders#2]
您好！我按提示装了  python 3.9, 同时下载了最新版的firefox， 用pip install 在dos下安装了selenium。 我同时下载了geckodriver  0.32， 把该exe文件放在gisaid_downloader.py同一个文件夹下面。当我运行gisaid_downloader.py的时候，报错如下：

Opening Browser...
Traceback (most recent call last):
  File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 465, in <module>
    spider_loop(
  File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 405, in spider_loop
    start(
  File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 368, in start
    d = webdriver.Firefox(
  File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 196, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

请问这个问题怎么解决。是不是找不到firefox的相关文件造成的。谢谢！

**Comment by c4-driod** [comment]
嗨，看了一下你的情况和报错。我没有遇到过这种情况，但你说对了，报错说的应该是：找不到firefox的启动文件。
可以试一下把火狐exe文件的路径作为参数传入初始化的对象中，如下图所示，在gisaid_downloader.py的第358行前面加上这一行，记得把“路径”换成你的火狐路径：



再或者重启一下试试。


***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c4-driod/GISAID-spiders"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 晚上6:30
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[c4-driod/GISAID-spiders] gisaid下载问题 (Issue #2)





 
您好！我按提示装了  python 3.9, 同时下载了最新版的firefox， 用pip install 在dos下安装了selenium。 我同时下载了geckodriver  0.32， 把该exe文件放在gisaid_downloader.py同一个文件夹下面。当我运行gisaid_downloader.py的时候，报错如下：
 
Opening Browser...
 Traceback (most recent call last):
 File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 465, in 
 spider_loop(
 File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 405, in spider_loop
 start(
 File "F:\GISAID\GISAID-spiders-main\gisaid_downloader.py", line 368, in start
 d = webdriver.Firefox(
 File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 196, in init
 super().init(command_executor=executor, options=options, keep_alive=True)
 File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in init
 self.start_session(capabilities, browser_profile)
 File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
 response = self.execute(Command.NEW_SESSION, parameters)
 File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
 self.error_handler.check_response(response)
 File "C:\Users\WXC\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
 raise exception_class(message, screen, stacktrace)
 selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
 
请问这个问题怎么解决。是不是找不到firefox的相关文件造成的。谢谢！

**Comment by scwwxc** [comment]
谢谢！应该怎么加呢？我这边看不到具体的图片。

**Comment by c4-driod** [comment]
用文本编辑器修改文本就可以了
&nbsp;


晓鸉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月31日(星期二) 晚上8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [c4-driod/GISAID-spiders] gisaid下载问题 (Issue #2)





 
谢谢！应该怎么加呢？我这边看不到具体的图片。

**Comment by c4-driod** [comment]
要不你直接加我QQ好友？1977649208




晓鸉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "c4-driod/GISAID-spiders"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月31日(星期二) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [c4-driod/GISAID-spiders] gisaid下载问题 (Issue #2)





 
谢谢！应该怎么加呢？我这边看不到具体的图片。

**Comment by scwwxc** [comment]
重启后可以下载了，十分感谢！
